[2023-06-19T10:52:38.606+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: azure_container_instances.run_container manual__2023-06-19T10:52:35.137262+00:00 [queued]>
[2023-06-19T10:52:38.634+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: azure_container_instances.run_container manual__2023-06-19T10:52:35.137262+00:00 [queued]>
[2023-06-19T10:52:38.634+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-19T10:52:38.659+0000] {taskinstance.py:1327} INFO - Executing <Task(AzureContainerInstancesOperator): run_container> on 2023-06-19 10:52:35.137262+00:00
[2023-06-19T10:52:38.663+0000] {standard_task_runner.py:57} INFO - Started process 28711 to run task
[2023-06-19T10:52:38.668+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'azure_container_instances', 'run_container', 'manual__2023-06-19T10:52:35.137262+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/dbt_docker.py', '--cfg-path', '/tmp/tmpscoco4vv']
[2023-06-19T10:52:38.669+0000] {standard_task_runner.py:85} INFO - Job 95: Subtask run_container
[2023-06-19T10:52:38.728+0000] {task_command.py:410} INFO - Running <TaskInstance: azure_container_instances.run_container manual__2023-06-19T10:52:35.137262+00:00 [running]> on host ubuntu.thbnzb0d3dmuziyfg2t53bofqb.tx.internal.cloudapp.net
[2023-06-19T10:52:38.817+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='azure_container_instances' AIRFLOW_CTX_TASK_ID='run_container' AIRFLOW_CTX_EXECUTION_DATE='2023-06-19T10:52:35.137262+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-19T10:52:35.137262+00:00'
[2023-06-19T10:52:38.826+0000] {base.py:73} INFO - Using connection ID 'azure_conn_container' for task execution.
[2023-06-19T10:52:38.827+0000] {base_azure.py:114} INFO - Getting connection using specific credentials and subscription_id.
[2023-06-19T10:52:38.828+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/satyam/.local/lib/python3.8/site-packages/airflow/providers/microsoft/azure/operators/container_instances.py", line 192, in execute
    self._ci_hook = AzureContainerInstanceHook(azure_conn_id=self.ci_conn_id)
  File "/home/satyam/.local/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/container_instance.py", line 50, in __init__
    self.connection = self.get_conn()
  File "/home/satyam/.local/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/base_azure.py", line 116, in get_conn
    credentials=ServicePrincipalCredentials(
  File "/home/satyam/.local/lib/python3.8/site-packages/msrestazure/azure_active_directory.py", line 355, in __init__
    self.set_token()
  File "/home/satyam/.local/lib/python3.8/site-packages/msrestazure/azure_active_directory.py", line 362, in set_token
    super(ServicePrincipalCredentials, self).set_token()
  File "/home/satyam/.local/lib/python3.8/site-packages/msrestazure/azure_active_directory.py", line 188, in set_token
    self._create_adal_context()
  File "/home/satyam/.local/lib/python3.8/site-packages/msrestazure/azure_active_directory.py", line 109, in _create_adal_context
    authority_url = authority_url + '/' + self._tenant
TypeError: can only concatenate str (not "NoneType") to str
[2023-06-19T10:52:38.842+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=azure_container_instances, task_id=run_container, execution_date=20230619T105235, start_date=20230619T105238, end_date=20230619T105238
[2023-06-19T10:52:38.868+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 95 for task run_container (can only concatenate str (not "NoneType") to str; 28711)
[2023-06-19T10:52:38.880+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-19T10:52:38.893+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
