[2023-06-14T14:16:31.116+0000] {processor.py:157} INFO - Started process (PID=1717) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:16:31.120+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:16:31.121+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:16:31.120+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:16:31.130+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:16:31.130+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open(manifest_path) as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: 'manifest.json'
[2023-06-14T14:16:31.131+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:16:31.355+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.243 seconds
[2023-06-14T14:17:18.739+0000] {processor.py:157} INFO - Started process (PID=1958) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:17:18.740+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:17:18.742+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:17:18.742+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:17:18.746+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:17:18.745+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: 'menifest.json'
[2023-06-14T14:17:18.746+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:17:18.775+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T14:17:33.659+0000] {processor.py:157} INFO - Started process (PID=2223) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:17:33.661+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:17:33.661+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:17:33.661+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:17:33.664+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:17:33.663+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: 'menifest.json'
[2023-06-14T14:17:33.664+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:17:33.694+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T14:18:48.940+0000] {processor.py:157} INFO - Started process (PID=2753) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:18:48.942+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:18:48.942+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:18:48.942+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:18:48.945+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:18:48.944+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:18:48.945+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:18:48.973+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.036 seconds
[2023-06-14T14:19:41.039+0000] {processor.py:157} INFO - Started process (PID=4144) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:19:41.040+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:19:41.043+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:19:41.043+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:19:41.046+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:19:41.045+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:19:41.046+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:19:41.073+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T14:20:20.471+0000] {processor.py:157} INFO - Started process (PID=4285) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:20:20.472+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:20:20.475+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:20:20.474+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:20:20.477+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:20:20.476+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:20:20.478+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:20:20.506+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T14:20:58.934+0000] {processor.py:157} INFO - Started process (PID=4427) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:20:58.935+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:20:58.937+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:20:58.937+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:20:58.940+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:20:58.939+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:20:58.940+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:20:58.968+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T14:21:33.815+0000] {processor.py:157} INFO - Started process (PID=4461) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:21:33.817+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:21:33.819+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:21:33.819+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:21:33.822+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:21:33.821+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:21:33.823+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:21:33.852+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.041 seconds
[2023-06-14T14:22:09.135+0000] {processor.py:157} INFO - Started process (PID=4606) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:22:09.137+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:22:09.139+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:22:09.139+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:22:09.142+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:22:09.141+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:22:09.142+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:22:09.170+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T14:22:46.072+0000] {processor.py:157} INFO - Started process (PID=4642) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:22:46.074+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:22:46.076+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:22:46.076+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:22:46.079+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:22:46.078+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:22:46.079+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:22:46.106+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.037 seconds
[2023-06-14T14:23:18.649+0000] {processor.py:157} INFO - Started process (PID=4781) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:23:18.650+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:23:18.653+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:23:18.653+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:23:18.655+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:23:18.655+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:23:18.656+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:23:18.684+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T14:23:50.730+0000] {processor.py:157} INFO - Started process (PID=4853) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:23:50.731+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:23:50.733+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:23:50.733+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:23:50.736+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:23:50.735+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:23:50.736+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:23:50.763+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.037 seconds
[2023-06-14T14:24:25.210+0000] {processor.py:157} INFO - Started process (PID=5054) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:24:25.212+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:24:25.214+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:24:25.214+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:24:25.217+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:24:25.216+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:24:25.217+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:24:25.245+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T14:24:59.088+0000] {processor.py:157} INFO - Started process (PID=5192) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:24:59.089+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:24:59.091+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:24:59.091+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:24:59.094+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:24:59.093+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:24:59.094+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:24:59.122+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T14:25:30.034+0000] {processor.py:157} INFO - Started process (PID=5225) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:25:30.035+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:25:30.038+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:25:30.038+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:25:30.040+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:25:30.040+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:25:30.041+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:25:30.067+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.037 seconds
[2023-06-14T14:26:05.191+0000] {processor.py:157} INFO - Started process (PID=5362) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:26:05.192+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:26:05.194+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:26:05.194+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:26:05.197+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:26:05.196+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:26:05.197+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:26:05.369+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.183 seconds
[2023-06-14T14:26:40.072+0000] {processor.py:157} INFO - Started process (PID=5400) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:26:40.074+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:26:40.076+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:26:40.076+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:26:40.079+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:26:40.078+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:26:40.079+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:26:40.106+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T14:27:14.749+0000] {processor.py:157} INFO - Started process (PID=5540) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:27:14.751+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:27:14.753+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:27:14.753+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:27:14.756+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:27:14.755+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:27:14.756+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:27:14.792+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.046 seconds
[2023-06-14T14:27:49.372+0000] {processor.py:157} INFO - Started process (PID=5576) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:27:49.374+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:27:49.377+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:27:49.376+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:27:49.379+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:27:49.378+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:27:49.380+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:27:49.407+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T14:28:25.764+0000] {processor.py:157} INFO - Started process (PID=5716) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:28:25.766+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:28:25.768+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:28:25.768+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:28:25.771+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:28:25.770+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:28:25.771+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:28:25.799+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T14:29:00.536+0000] {processor.py:157} INFO - Started process (PID=5958) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:29:00.537+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:29:00.540+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:29:00.539+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:29:00.542+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:29:00.541+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:29:00.543+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:29:00.572+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.040 seconds
[2023-06-14T14:29:32.369+0000] {processor.py:157} INFO - Started process (PID=5992) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:29:32.371+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:29:32.373+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:29:32.373+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:29:32.376+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:29:32.375+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:29:32.376+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:29:32.405+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.040 seconds
[2023-06-14T14:30:09.183+0000] {processor.py:157} INFO - Started process (PID=6130) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:30:09.184+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:30:09.187+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:30:09.186+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:30:09.189+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:30:09.188+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:30:09.190+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:30:09.221+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.042 seconds
[2023-06-14T14:30:47.476+0000] {processor.py:157} INFO - Started process (PID=6169) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:30:47.477+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:30:47.480+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:30:47.480+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:30:47.482+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:30:47.481+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:30:47.483+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:30:47.511+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T14:31:22.412+0000] {processor.py:157} INFO - Started process (PID=6307) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:31:22.414+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:31:22.416+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:31:22.416+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:31:22.419+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:31:22.418+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:31:22.419+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:31:22.448+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T14:31:56.809+0000] {processor.py:157} INFO - Started process (PID=6446) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:31:56.811+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:31:56.813+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:31:56.813+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:31:56.816+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:31:56.815+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:31:56.816+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:31:56.843+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T14:32:30.799+0000] {processor.py:157} INFO - Started process (PID=6487) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:32:30.800+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:32:30.803+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:32:30.802+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:32:30.805+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:32:30.804+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:32:30.806+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:32:30.833+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T14:33:03.913+0000] {processor.py:157} INFO - Started process (PID=6624) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:33:03.914+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:33:03.916+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:33:03.916+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:33:03.919+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:33:03.918+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:33:03.919+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:33:03.955+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.046 seconds
[2023-06-14T14:33:37.213+0000] {processor.py:157} INFO - Started process (PID=6658) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:33:37.215+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:33:37.217+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:33:37.217+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:33:37.220+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:33:37.219+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:33:37.220+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:33:37.247+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T14:34:13.568+0000] {processor.py:157} INFO - Started process (PID=6898) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:34:13.570+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:34:13.572+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:34:13.572+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:34:13.576+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:34:13.574+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:34:13.576+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:34:13.609+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.046 seconds
[2023-06-14T14:34:50.210+0000] {processor.py:157} INFO - Started process (PID=6936) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:34:50.212+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:34:50.214+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:34:50.214+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:34:50.217+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:34:50.216+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:34:50.217+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:34:50.246+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.040 seconds
[2023-06-14T14:35:24.658+0000] {processor.py:157} INFO - Started process (PID=7077) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:35:24.659+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:35:24.662+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:35:24.662+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:35:24.664+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:35:24.664+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:35:24.665+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:35:24.691+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.037 seconds
[2023-06-14T14:35:59.851+0000] {processor.py:157} INFO - Started process (PID=7217) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:35:59.852+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:35:59.854+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:35:59.854+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:35:59.857+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:35:59.856+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:35:59.857+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:35:59.884+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.037 seconds
[2023-06-14T14:36:33.559+0000] {processor.py:157} INFO - Started process (PID=7252) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:36:33.560+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:36:33.563+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:36:33.562+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:36:33.565+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:36:33.564+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:36:33.566+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:36:33.595+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.040 seconds
[2023-06-14T14:37:08.312+0000] {processor.py:157} INFO - Started process (PID=7396) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:37:08.313+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:37:08.315+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:37:08.315+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:37:08.318+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:37:08.317+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:37:08.318+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:37:08.347+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.040 seconds
[2023-06-14T14:37:43.008+0000] {processor.py:157} INFO - Started process (PID=7431) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:37:43.009+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:37:43.011+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:37:43.011+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:37:43.014+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:37:43.013+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:37:43.014+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:37:43.041+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.037 seconds
[2023-06-14T14:38:16.867+0000] {processor.py:157} INFO - Started process (PID=7569) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:38:16.869+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:38:16.871+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:38:16.871+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:38:16.874+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:38:16.873+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:38:16.874+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:38:16.907+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.044 seconds
[2023-06-14T14:38:50.268+0000] {processor.py:157} INFO - Started process (PID=7603) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:38:50.269+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:38:50.272+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:38:50.271+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:38:50.274+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:38:50.273+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:38:50.275+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:38:50.301+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T14:39:21.375+0000] {processor.py:157} INFO - Started process (PID=7738) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:39:21.376+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:39:21.378+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:39:21.378+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:39:21.381+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:39:21.380+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:39:21.382+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:39:21.425+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.056 seconds
[2023-06-14T14:39:55.161+0000] {processor.py:157} INFO - Started process (PID=7874) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:39:55.162+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:39:55.165+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:39:55.164+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:39:55.167+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:39:55.166+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:39:55.168+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:39:55.195+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T14:40:30.910+0000] {processor.py:157} INFO - Started process (PID=7911) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:40:30.912+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:40:30.914+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:40:30.914+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:40:30.917+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:40:30.916+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:40:30.917+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:40:30.951+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.045 seconds
[2023-06-14T14:41:07.518+0000] {processor.py:157} INFO - Started process (PID=8050) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:41:07.520+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:41:07.522+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:41:07.522+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:41:07.525+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:41:07.524+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:41:07.525+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:41:07.555+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.041 seconds
[2023-06-14T14:41:43.545+0000] {processor.py:157} INFO - Started process (PID=8087) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:41:43.547+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:41:43.549+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:41:43.549+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:41:43.552+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:41:43.551+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:41:43.552+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:41:43.583+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.042 seconds
[2023-06-14T14:42:19.055+0000] {processor.py:157} INFO - Started process (PID=8230) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:42:19.058+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:42:19.060+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:42:19.060+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:42:19.063+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:42:19.062+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:42:19.063+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:42:19.094+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.043 seconds
[2023-06-14T14:42:55.704+0000] {processor.py:157} INFO - Started process (PID=8369) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:42:55.706+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:42:55.708+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:42:55.708+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:42:55.711+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:42:55.710+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:42:55.711+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:42:55.739+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T14:43:33.953+0000] {processor.py:157} INFO - Started process (PID=8407) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:43:33.954+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:43:33.957+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:43:33.957+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:43:33.960+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:43:33.959+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:43:33.960+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:43:33.987+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.037 seconds
[2023-06-14T14:44:10.621+0000] {processor.py:157} INFO - Started process (PID=8648) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:44:10.623+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:44:10.625+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:44:10.625+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:44:10.628+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:44:10.627+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:44:10.628+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:44:10.653+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.036 seconds
[2023-06-14T14:44:46.841+0000] {processor.py:157} INFO - Started process (PID=8683) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:44:46.843+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:44:46.845+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:44:46.845+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:44:46.848+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:44:46.847+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:44:46.848+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:44:46.874+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.037 seconds
[2023-06-14T14:45:23.663+0000] {processor.py:157} INFO - Started process (PID=8824) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:45:23.665+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:45:23.668+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:45:23.668+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:45:23.671+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:45:23.671+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:45:23.672+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:45:23.713+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.054 seconds
[2023-06-14T14:46:02.015+0000] {processor.py:157} INFO - Started process (PID=8967) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:46:02.017+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:46:02.019+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:46:02.019+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:46:02.022+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:46:02.021+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:46:02.022+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:46:02.049+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.037 seconds
[2023-06-14T14:46:39.205+0000] {processor.py:157} INFO - Started process (PID=9005) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:46:39.206+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:46:39.208+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:46:39.208+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:46:39.211+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:46:39.210+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:46:39.211+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:46:39.237+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.036 seconds
[2023-06-14T14:47:11.237+0000] {processor.py:157} INFO - Started process (PID=9144) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:47:11.239+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:47:11.241+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:47:11.241+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:47:11.244+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:47:11.243+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:47:11.244+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:47:11.272+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T14:47:48.500+0000] {processor.py:157} INFO - Started process (PID=9181) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:47:48.502+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:47:48.504+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:47:48.504+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:47:48.507+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:47:48.506+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:47:48.507+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:47:48.536+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T14:48:22.257+0000] {processor.py:157} INFO - Started process (PID=9318) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:48:22.258+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:48:22.260+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:48:22.260+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:48:22.263+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:48:22.262+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:48:22.263+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:48:22.289+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.036 seconds
[2023-06-14T14:48:59.620+0000] {processor.py:157} INFO - Started process (PID=9560) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:48:59.622+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:48:59.624+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:48:59.624+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:48:59.627+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:48:59.626+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:48:59.627+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:48:59.653+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.037 seconds
[2023-06-14T14:49:36.353+0000] {processor.py:157} INFO - Started process (PID=9596) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:49:36.354+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:49:36.357+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:49:36.356+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:49:36.360+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:49:36.359+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:49:36.360+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:49:36.393+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.045 seconds
[2023-06-14T14:50:14.513+0000] {processor.py:157} INFO - Started process (PID=9737) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:50:14.514+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:50:14.516+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:50:14.516+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:50:14.519+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:50:14.518+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:50:14.519+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:50:14.547+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T14:50:49.456+0000] {processor.py:157} INFO - Started process (PID=9773) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:50:49.457+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:50:49.460+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:50:49.460+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:50:49.462+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:50:49.462+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:50:49.463+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:50:49.491+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T14:51:22.601+0000] {processor.py:157} INFO - Started process (PID=9911) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:51:22.603+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:51:22.605+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:51:22.605+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:51:22.608+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:51:22.607+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:51:22.608+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:51:22.636+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T14:51:53.618+0000] {processor.py:157} INFO - Started process (PID=10046) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:51:53.619+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:51:53.622+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:51:53.621+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:51:53.624+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:51:53.623+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:51:53.625+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:51:53.654+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.040 seconds
[2023-06-14T14:52:25.812+0000] {processor.py:157} INFO - Started process (PID=10084) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:52:25.813+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:52:25.816+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:52:25.815+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:52:25.818+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:52:25.817+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:52:25.819+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:52:25.845+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.037 seconds
[2023-06-14T14:53:00.579+0000] {processor.py:157} INFO - Started process (PID=10222) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:53:00.581+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:53:00.583+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:53:00.583+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:53:00.586+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:53:00.585+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:53:00.586+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:53:00.611+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.036 seconds
[2023-06-14T14:53:35.463+0000] {processor.py:157} INFO - Started process (PID=10257) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:53:35.465+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:53:35.468+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:53:35.467+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:53:35.470+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:53:35.469+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:53:35.471+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:53:35.497+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T14:54:11.736+0000] {processor.py:157} INFO - Started process (PID=10500) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:54:11.737+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:54:11.740+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:54:11.740+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:54:11.742+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:54:11.742+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:54:11.743+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:54:11.778+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.047 seconds
[2023-06-14T14:54:47.923+0000] {processor.py:157} INFO - Started process (PID=10537) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:54:47.925+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:54:47.927+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:54:47.927+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:54:47.930+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:54:47.929+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:54:47.930+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:54:47.960+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.041 seconds
[2023-06-14T14:55:22.247+0000] {processor.py:157} INFO - Started process (PID=10776) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:55:22.248+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:55:22.250+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:55:22.250+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:55:22.253+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:55:22.252+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:55:22.253+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:55:22.281+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T14:55:57.871+0000] {processor.py:157} INFO - Started process (PID=10916) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:55:57.873+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:55:57.875+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:55:57.875+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:55:57.878+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:55:57.877+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:55:57.878+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:55:57.910+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.043 seconds
[2023-06-14T14:56:32.200+0000] {processor.py:157} INFO - Started process (PID=10951) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:56:32.201+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:56:32.204+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:56:32.204+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:56:32.206+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:56:32.206+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:56:32.207+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:56:32.233+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T14:57:07.058+0000] {processor.py:157} INFO - Started process (PID=11095) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:57:07.060+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:57:07.062+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:57:07.062+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:57:07.065+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:57:07.064+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:57:07.065+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:57:07.091+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.037 seconds
[2023-06-14T14:57:39.227+0000] {processor.py:157} INFO - Started process (PID=11127) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:57:39.228+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:57:39.230+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:57:39.230+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:57:39.233+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:57:39.232+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:57:39.233+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:57:39.261+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T14:58:14.129+0000] {processor.py:157} INFO - Started process (PID=11265) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:58:14.131+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:58:14.133+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:58:14.133+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:58:14.136+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:58:14.135+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:58:14.136+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:58:14.163+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T14:58:49.837+0000] {processor.py:157} INFO - Started process (PID=11301) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:58:49.839+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:58:49.842+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:58:49.841+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:58:49.844+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:58:49.843+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:58:49.845+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:58:49.871+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T14:59:32.903+0000] {processor.py:157} INFO - Started process (PID=11552) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:59:32.905+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T14:59:32.907+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:59:32.907+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:59:32.910+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:59:32.909+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T14:59:32.910+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T14:59:32.937+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T15:00:06.196+0000] {processor.py:157} INFO - Started process (PID=11691) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:00:06.197+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:00:06.199+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:00:06.199+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:00:06.202+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:00:06.201+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:00:06.202+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:00:06.237+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.045 seconds
[2023-06-14T15:00:40.048+0000] {processor.py:157} INFO - Started process (PID=11725) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:00:40.049+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:00:40.051+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:00:40.051+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:00:40.054+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:00:40.053+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:00:40.054+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:00:40.081+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.037 seconds
[2023-06-14T15:01:14.663+0000] {processor.py:157} INFO - Started process (PID=11865) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:01:14.665+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:01:14.667+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:01:14.667+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:01:14.670+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:01:14.669+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:01:14.670+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:01:14.698+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T15:01:49.599+0000] {processor.py:157} INFO - Started process (PID=11901) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:01:49.601+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:01:49.603+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:01:49.603+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:01:49.606+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:01:49.605+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:01:49.606+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:01:49.633+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T15:02:22.779+0000] {processor.py:157} INFO - Started process (PID=12046) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:02:22.780+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:02:22.783+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:02:22.782+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:02:22.785+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:02:22.784+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:02:22.786+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:02:22.812+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.037 seconds
[2023-06-14T15:02:56.261+0000] {processor.py:157} INFO - Started process (PID=12185) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:02:56.262+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:02:56.264+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:02:56.264+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:02:56.267+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:02:56.266+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:02:56.267+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:02:56.295+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T15:03:30.883+0000] {processor.py:157} INFO - Started process (PID=12321) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:03:30.885+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:03:30.887+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:03:30.887+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:03:30.890+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:03:30.889+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:03:30.890+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:03:30.919+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.040 seconds
[2023-06-14T15:04:05.929+0000] {processor.py:157} INFO - Started process (PID=12564) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:04:05.931+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:04:05.933+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:04:05.933+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:04:05.936+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:04:05.935+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:04:05.936+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:04:05.968+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.043 seconds
[2023-06-14T15:04:40.036+0000] {processor.py:157} INFO - Started process (PID=12598) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:04:40.037+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:04:40.040+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:04:40.039+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:04:40.042+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:04:40.042+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:04:40.043+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:04:40.071+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T15:05:16.579+0000] {processor.py:157} INFO - Started process (PID=12974) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:05:16.585+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:05:16.605+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:05:16.605+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:05:16.609+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:05:16.608+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:05:16.610+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:05:16.715+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.148 seconds
[2023-06-14T15:05:55.321+0000] {processor.py:157} INFO - Started process (PID=13116) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:05:55.322+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:05:55.325+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:05:55.324+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:05:55.327+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:05:55.326+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:05:55.328+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:05:55.358+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.041 seconds
[2023-06-14T15:06:30.370+0000] {processor.py:157} INFO - Started process (PID=13152) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:06:30.372+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:06:30.374+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:06:30.374+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:06:30.377+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:06:30.376+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:06:30.377+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:06:30.411+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.044 seconds
[2023-06-14T15:07:03.774+0000] {processor.py:157} INFO - Started process (PID=13398) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:07:03.776+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:07:03.779+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:07:03.779+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:07:03.782+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:07:03.781+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:07:03.782+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:07:03.809+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T15:07:37.472+0000] {processor.py:157} INFO - Started process (PID=13442) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:07:37.473+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:07:37.476+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:07:37.475+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:07:37.478+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:07:37.478+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:07:37.479+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:07:37.507+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T15:08:11.933+0000] {processor.py:157} INFO - Started process (PID=13580) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:08:11.935+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:08:11.937+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:08:11.937+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:08:11.940+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:08:11.939+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:08:11.941+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:08:11.973+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.044 seconds
[2023-06-14T15:08:45.659+0000] {processor.py:157} INFO - Started process (PID=13615) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:08:45.661+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:08:45.663+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:08:45.663+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:08:45.666+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:08:45.665+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:08:45.666+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:08:45.694+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T15:09:17.722+0000] {processor.py:157} INFO - Started process (PID=13854) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:09:17.723+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:09:17.726+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:09:17.726+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:09:17.728+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:09:17.728+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:09:17.729+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:09:17.758+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T15:09:50.675+0000] {processor.py:157} INFO - Started process (PID=13887) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:09:50.676+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:09:50.679+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:09:50.679+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:09:50.682+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:09:50.681+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:09:50.682+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:09:50.710+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T15:10:26.086+0000] {processor.py:157} INFO - Started process (PID=14025) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:10:26.087+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:10:26.090+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:10:26.090+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:10:26.092+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:10:26.091+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:10:26.093+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:10:26.123+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.041 seconds
[2023-06-14T15:10:58.073+0000] {processor.py:157} INFO - Started process (PID=14164) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:10:58.074+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:10:58.076+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:10:58.076+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:10:58.079+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:10:58.078+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:10:58.079+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:10:58.107+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T15:11:44.554+0000] {processor.py:157} INFO - Started process (PID=14212) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:11:44.556+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:11:44.559+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:11:44.558+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:11:44.561+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:11:44.560+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:11:44.562+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:11:44.588+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
[2023-06-14T15:12:20.832+0000] {processor.py:157} INFO - Started process (PID=14358) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:12:20.833+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:12:20.835+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:12:20.835+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:12:20.838+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:12:20.837+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:12:20.838+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:12:20.866+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.039 seconds
[2023-06-14T15:12:54.462+0000] {processor.py:157} INFO - Started process (PID=14493) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:12:54.463+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:12:54.466+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:12:54.466+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:12:54.469+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:12:54.468+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:12:54.469+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:12:54.498+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.040 seconds
[2023-06-14T15:13:30.218+0000] {processor.py:157} INFO - Started process (PID=14530) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:13:30.219+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:13:30.222+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:13:30.222+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:13:30.225+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:13:30.224+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:13:30.225+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:13:30.255+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.041 seconds
[2023-06-14T15:14:03.827+0000] {processor.py:157} INFO - Started process (PID=14770) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:14:03.829+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:14:03.831+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:14:03.831+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:14:03.834+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:14:03.833+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:14:03.834+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:14:03.863+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.041 seconds
[2023-06-14T15:14:35.143+0000] {processor.py:157} INFO - Started process (PID=14805) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:14:35.144+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:14:35.147+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:14:35.147+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:14:35.150+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:14:35.149+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:14:35.150+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:14:35.178+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.040 seconds
[2023-06-14T15:15:09.195+0000] {processor.py:157} INFO - Started process (PID=14941) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:15:09.196+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:15:09.199+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:15:09.199+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:15:09.202+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:15:09.201+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:15:09.202+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:15:09.232+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.042 seconds
[2023-06-14T15:15:43.576+0000] {processor.py:157} INFO - Started process (PID=14976) to work on /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:15:43.577+0000] {processor.py:826} INFO - Processing file /home/satyam/airflow/dags/dbt_dag.py for tasks to queue
[2023-06-14T15:15:43.579+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:15:43.579+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:15:43.582+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:15:43.581+0000] {dagbag.py:350} ERROR - Failed to import: /home/satyam/airflow/dags/dbt_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/satyam/airflow/dags/dbt_dag.py", line 11, in <module>
    with open('./menifest.json') as f: # Open manifest.json
FileNotFoundError: [Errno 2] No such file or directory: './menifest.json'
[2023-06-14T15:15:43.582+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/satyam/airflow/dags/dbt_dag.py
[2023-06-14T15:15:43.610+0000] {processor.py:179} INFO - Processing /home/satyam/airflow/dags/dbt_dag.py took 0.038 seconds
