[2023-06-19T11:05:13.920+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: azure_container_instances.run_container manual__2023-06-19T11:05:10.627376+00:00 [queued]>
[2023-06-19T11:05:13.929+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: azure_container_instances.run_container manual__2023-06-19T11:05:10.627376+00:00 [queued]>
[2023-06-19T11:05:13.929+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-19T11:05:13.957+0000] {taskinstance.py:1327} INFO - Executing <Task(AzureContainerInstancesOperator): run_container> on 2023-06-19 11:05:10.627376+00:00
[2023-06-19T11:05:13.961+0000] {standard_task_runner.py:57} INFO - Started process 32444 to run task
[2023-06-19T11:05:13.965+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'azure_container_instances', 'run_container', 'manual__2023-06-19T11:05:10.627376+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/dbt_docker.py', '--cfg-path', '/tmp/tmpriexwyle']
[2023-06-19T11:05:13.966+0000] {standard_task_runner.py:85} INFO - Job 99: Subtask run_container
[2023-06-19T11:05:14.027+0000] {task_command.py:410} INFO - Running <TaskInstance: azure_container_instances.run_container manual__2023-06-19T11:05:10.627376+00:00 [running]> on host ubuntu.thbnzb0d3dmuziyfg2t53bofqb.tx.internal.cloudapp.net
[2023-06-19T11:05:14.114+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='azure_container_instances' AIRFLOW_CTX_TASK_ID='run_container' AIRFLOW_CTX_EXECUTION_DATE='2023-06-19T11:05:10.627376+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-19T11:05:10.627376+00:00'
[2023-06-19T11:05:14.117+0000] {connection.py:428} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/connection.py", line 424, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
  File "/usr/local/lib/python3.8/dist-packages/airflow/secrets/base_secrets.py", line 95, in get_connection
    value = self.get_conn_value(conn_id=conn_id)
  File "/usr/local/lib/python3.8/dist-packages/airflow/secrets/environment_variables.py", line 49, in get_conn_value
    return os.environ.get(CONN_ENV_PREFIX + conn_id.upper())
AttributeError: 'NoneType' object has no attribute 'upper'
[2023-06-19T11:05:14.128+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/satyam/.local/lib/python3.8/site-packages/airflow/providers/microsoft/azure/operators/container_instances.py", line 192, in execute
    self._ci_hook = AzureContainerInstanceHook(azure_conn_id=self.ci_conn_id)
  File "/home/satyam/.local/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/container_instance.py", line 50, in __init__
    self.connection = self.get_conn()
  File "/home/satyam/.local/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/base_azure.py", line 96, in get_conn
    conn = self.get_connection(self.conn_id)
  File "/usr/local/lib/python3.8/dist-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `None` isn't defined
[2023-06-19T11:05:14.131+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=azure_container_instances, task_id=run_container, execution_date=20230619T110510, start_date=20230619T110513, end_date=20230619T110514
[2023-06-19T11:05:14.156+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 99 for task run_container (The conn_id `None` isn't defined; 32444)
[2023-06-19T11:05:14.177+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-19T11:05:14.192+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
